
services:
 
  backend:
    build: backend
    command: npm start
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    

  frontend:
    build:
      context: ./frontend
    command: "npm run dev"
    ports:
      - '5173:5173'
    
